### ISSUE TITLE
expire time

### ISSUE THREAD

**Issue by Fabbryzz** [paolobasso99/herbyCookie#1]
Hi Paolo, great work, but I have a question about your plugin:
Is it possible to set the time of expiring cookie consent?

**Comment by paolobasso99** [comment]
Mh, nice idea. Tomorrow I'll see if i can add expire time at my plugin.

Paolo Basso

**Comment by paolobasso99** [comment]
Hi Fabbryzz, thank you for your advice, since version 1.1 (just relased)  herbyCookie supports "expireDays" option. You can see the [Changelog](https://github.com/paolobasso99/herbyCookie/blob/master/changelog.md) and the new [Instructions](https://github.com/paolobasso99/herbyCookie/blob/master/README.md).
Paolo Basso.

**Comment by Fabbryzz** [comment]
Great work Paolo, thank you! ;-)
